### PR TITLE
Fixed dependencies

### PR DESCRIPTION
**Pull request by DerZyklop**
`npm i` caused a bunch of `UNMET PEER DEPENDENCY` errors and the "No repository field" warning.

### CODE REVIEW

**Comment by gonzofish** [comment]
I merged this in, but I have a new article coming out and I made a slightly different fix, which updates RxJS and removes some outdated dependencies. Thanks for the fixes!

**Comment by DerZyklop** [comment]
@gonzofish good to know. 

btw: did you manage to get the tests running? i updated webpack and karma-webpack. and always get `ERROR [preprocess]: Can not load “webpack”!` 

I tried different »solutions« in our app which is based on your tutorial. And i did the same in a clean install of your repo. No success :/ 

I also [posted it on stackoverflow](http://stackoverflow.com/questions/42188716/error-preprocess-can-not-load-webpack-webpack2-2-1-karma1-4-1).

I really don’t want to waste your time, but maybe you have a clue whats happening here? I‘m hopeless right now.

**Comment by gonzofish** [comment]
I won't say this is going to solve it, but if you're using Webpack 2, you'll need to move the TSLint `preLoader` into the `loaders` array and mark it with `enforce: 'pre'` (see [this file in another of my repos](https://github.com/gonzofish/angular-library-set/blob/master/commands/initial/templates/webpack/webpack.test.js)).

The repo in that link is for a Angular 2 project generator, but has all the files you'd need for a Webpack 2 setup. Take a look: https://github.com/gonzofish/angular-library-set/tree/master/commands/initial/templates. I'd say the important files for you to look at are `package.json`, `src/test.js` and `webpack/webpack.test.js`. 

Just know that in any file if you see `{{ someVariable }}` that's something the generator replaces and files like `__gitignore` and `__npmignore` become `.gitignore` and `.npmignore`.

Good luck! Thanks for reading!

**Comment by gonzofish** [comment]
Also, if you have a public repo I can look at, I might have some time to look at it.

**Comment by DerZyklop** [comment]
THANK YOU!!

My tests are finally running. Im not quite sure what exactly caused the issue, tho. But i can say it was inside **webpack.test.js**. What i changed was:

added `performance: { hints: false },` added `istanbul-instrumenter-loader`, took the `plugins` and `resolve` section from your link.

**Comment by gonzofish** [comment]
Great! I think it was a combination of the `plugins` and `resolve` sections--but I obviously can't be sure

**Comment by DerZyklop** [comment]
uh.. i think i got it. I removed 

    tslint: {
        emitErrors: true
    }

when i add it back, this comes back: 

    ERROR [preprocess]: Can not load “webpack”!

**Comment by gonzofish** [comment]
oh, I get why now--Webpack 2 has a very strict configuration--that was moved to the `plugins` section using the `webpack.LoaderOptionsPlugin`:

```javascript
        new LoaderOptionsPlugin({
            options: {
                emitErrors: true
            }
        }),
```

Webpack does some nice config checking right now, but it comes with some major differences in what is and isn't allowed in the configuration files.

**Comment by DerZyklop** [comment]
aah.. i see! Webpack is still kind of a jungle for me. Good to have this clear now. 

Thanks for the help. And also: You helped us a lot with your tutorial! So thanks for that, too. 

Keep the good work going, and have a nice day! ✌️

**Pull request merged**
